### ISSUE TITLE
Driver Incorrect number of bytes read from connection

### ISSUE THREAD

**Issue by ernestas-poskus** [quux00/ogonori#18]
Hey @quux00 

I get quite a lot of these errors when working/testing driver:

```
github.com/quux00/ogonori/obinary/dbCommands.go:161; cause: Incorrect number of bytes read from connection. Expected: 48455; Actual: 32753
github.com/quux00/ogonori/obinary/qrycmd.go:263; cause: sessionId from server (1313622350) does not match client sessionId (321)
github.com/quux00/ogonori/obinary/qrycmd.go:263; cause: sessionId from server (2083927097) does not match client sessionId (321)
github.com/quux00/ogonori/obinary/qrycmd.go:263; cause: sessionId from server (1752522610) does not match client sessionId (321)
```

ideas ?

**Comment by quux00** [comment]
When you are getting this error, are you inserting []byte as BINARY type or doing something else?

This is potentially a duplicate of Issue #7 - this is the error you get when you insert a "large" binary type ([]byte).  "Large" seems to vary - I could do up to 65K on my Linux system, but only a few K on my Windows system.

I haven't diagnosed the problem yet.

So:
1) if you are doing []byte/BINARY, let's close this and put the error mesage into Issue #7 
2) let me know if you want to work on this; if not, I'll move it up my priority list

For now, just insert smaller []byte slices so you can make progress on whatever you are working on.

**Comment by ernestas-poskus** [comment]
I am inserting large string formatted with Sprintf, I will dig deeper into driver in order to solve all these issues.

Now I will focus on rewriting/writing tests for current functionality to be able to 'safely refactor' later
