### ISSUE TITLE
Server and client session ids do not match

### ISSUE THREAD

**Issue by larryaasen** [quux00/ogonori#4]
I often see an error about server and client session ids not matching. Here is one case:
```
OrientDB.runSQLQuery: github.com/quux00/ogonori/obinary/qrycmd.go:98; cause: sessionId from server (6) does not match client sessionId (1773), SELECT FROM Post WHERE @RID=?
GetTimeline postRid:  #14:3
```
I am not sure how I could make the session ids not match. Can you explain what may be causing this?

**Comment by quux00** [comment]
I would have to see the context of your queries/commands and when the error occurs to be sure.  I usually see it when a query has failed and then I go on to try to do additional things, such as cleanup (deleting records, dropping classes, etc.)

As background, in order for a client to speak to the OrientDB server it has to first make a connection to either the server or a database and get a session-id.  You can only be connected to one database at a time.  I think it is also the case you can only be connected to either the database or the server but not both at the same time (I'd have to double check that).  

Once a connection is lost that session is closed down.  The connection can be closed by calling CloseDatabase.  The session is probably also lost when some errors happens, but I haven't fully tracked down the behavior of the server under various error conditions.

So the error you see is when the client has cached a session-id that the server no longer thinks is valid.  Error detection/handling, or at least error reporting of these scenarios, is something I will need to make better as the driver improves.

It would be useful for me if you can post the code that you invoke that causes this and what you were calling before it.  You can also turn debugging mode on on the server and see if it spits out errors and closes the connection when this happens.  You can do that by modifying the OrientDB server config file with:

    <listener protocol="binary" port-range="2424-2430" ip-address="127.0.0.1">
      <parameters>
        <parameter name="network.binary.debug" value="true" />
      </parameters>
    </listener>

**Comment by larryaasen** [comment]
I'm guessing that my problem was either using two threads with the same connection, or not closing a connection properly. It may take a while to figure this out, but I have made changes that may avoid it in the future. Thanks for your help.
